name: Android CI

on:
  push:
    tags:
      - 'vf*'

jobs:
  build-and-test:
    name: Build, Test, and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode google-services.json
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Decode Firebase Admin SDK
        run: |
          echo $FIREBASE_AUTH_TOKEN | base64 --decode > app/firebase-adminsdk.json
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}

      - name: Set up Firebase CLI
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=app/firebase-adminsdk.json

      - name: Verify Firebase Credentials File
        run: ls -l app/firebase-adminsdk.json

      - name: Debug GOOGLE_APPLICATION_CREDENTIALS
        run: echo $GOOGLE_APPLICATION_CREDENTIALS
        env:
          GOOGLE_APPLICATION_CREDENTIALS: app/firebase-adminsdk.json

      - name: Set File Permissions
        run: chmod 600 app/firebase-adminsdk.json

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar

      - name: Display Firebase Admin SDK Content
        run: cat app/firebase-adminsdk.json

      - name: Upload APK to Firebase
        run: ./gradlew appDistributionUploadRelease
        env:
          GOOGLE_APPLICATION_CREDENTIALS: app/firebase-adminsdk.json