name: Android ci

on:
  push:
    branches:
      - main
      
jobs:
  build-and-test:
    name: Build, Test, and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33               # API Level de l'émulateur
        build-tools: 33.0.3         # Outils de compilation pour l'API 33

    - name: Start Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33               
        target: google_apis         
        arch: x86_64                
        profile: Pixel 8 Pro       
        emulator-options: -no-snapshot-save
        script: ./gradlew connectedAndroidTest

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Install dependencies
      run: ./gradlew dependencies

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Run Instrumented Tests
      run: ./gradlew connectedAndroidTest

    - name: SonarCloud Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonar