name: Android CI with Firebase

on:
  push:
    branches:
      - main

jobs:
  build-test-publish:
    name: Build, Test, Sonar, and Firebase Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'


      - name: Add google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json

      - name: Set up Firebase CLI
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/firebase-service-account.json

      - name: Upload APK to Firebase
        run: ./gradlew appDistributionUploadRelease
        env:
          GOOGLE_APPLICATION_CREDENTIALS: app/firebase-service-account.json


      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Run Unit Tests
        run: ./gradlew test

      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube

      - name: Upload to Firebase App Distribution
        env:
          FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
        run: |
          ./gradlew appDistributionUploadRelease