name: Android ci

on:
  pull_request:
    branches:
      - main
      
jobs:
  build-and-test:
    name: Build, Test, and SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Install dependencies
      run: ./gradlew dependencies

    - name: Run Unit Tests
      run: ./gradlew test

    - name: Run Instrumented Tests
      run: ./gradlew connectedAndroidTest

    - name: SonarCloud Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew sonar